Update tasks.yml

diff --git a/.tekton/tasks.yml b/.tekton/tasks.yml
--- a/.tekton/tasks.yml
+++ b/.tekton/tasks.yml
@@ -1,6 +1,5 @@
 ---
-#Task: To clean up
-
+#task Create cleanup Tekton task
 apiVersion: tekton.dev/v1beta1
 kind: Task
 name: cleanup
@@ -35,3 +34,26 @@ spec:
           rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
         fi
 
+---
+#Create test Tekton task
+apiVersion: tekton.dev/v1beta1
+kind: Task
+name: nose
+spec:
+  workspaces:
+    - name: source
+  params:
+    - name: args
+      description: Arguments to pass to nose
+      type: string
+      default: "-v"
+  steps:
+    - name: nosetests
+      image: python:3.9-slim
+      workingDir: $(workspaces.source.path)
+      script: |
+        #!/bin/bash
+        set -e
+        python -m pip install --upgrade pip wheel
+        pip install -r requirements.txt
+        nosetests $(params.args)
